# Generated by Django 3.1.7 on 2021-03-26 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('age', models.PositiveSmallIntegerField()),
                ('birth_date', models.DateField()),
                ('job_title', models.CharField(max_length=40)),
                ('employer', models.CharField(max_length=40)),
                ('location', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('phone_number', models.CharField(max_length=40)),
                ('profile_picture', models.ImageField(upload_to='')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
