# Generated by Django 3.1.7 on 2021-03-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscard',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
