# Generated by Django 3.1.7 on 2021-03-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20210326_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscard',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='MEDIA/'),
        ),
    ]
