# Generated by Django 3.1.7 on 2021-03-27 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20210326_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscard',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='businesscard',
            name='birth_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='businesscard',
            name='email',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='businesscard',
            name='employer',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='businesscard',
            name='first_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='businesscard',
            name='job_title',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='businesscard',
            name='last_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='businesscard',
            name='location',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='businesscard',
            name='phone_number',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
