# Generated by Django 3.1.7 on 2021-03-27 03:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0006_auto_20210326_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesscard',
            name='id',
        ),
        migrations.AlterField(
            model_name='businesscard',
            name='age',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='businesscard',
            name='birth_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='businesscard',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
