# Generated by Django 3.1.7 on 2021-03-24 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('age', models.PositiveSmallIntegerField()),
                ('birth_date', models.DateField()),
                ('job_title', models.CharField(max_length=40)),
                ('employer', models.CharField(max_length=40)),
                ('location', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('phonenumber', models.CharField(max_length=40)),
                ('profilepicture', models.BinaryField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.accounts')),
            ],
        ),
    ]
