# Generated by Django 3.1.7 on 2021-03-24 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210324_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phonenumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='profilepicture',
            new_name='profile_picture',
        ),
    ]
