# Generated by Django 3.1.7 on 2021-03-24 23:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_auto_20210324_1607'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BusinessCards',
            new_name='BusinessCard',
        ),
    ]
